# Generated by Django 5.0 on 2023-12-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studens',
            new_name='Movies',
        ),
    ]
