# Generated by Django 5.0 on 2023-12-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_studens_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
