# Generated by Django 5.0 on 2023-12-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
