# Generated by Django 5.0 on 2023-12-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdb',
            field=models.IntegerField(null=True),
        ),
    ]
