# Generated by Django 5.0 on 2023-12-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movies_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
